author:
  name: "Trevor SANDY"

social:
  - {icon: 'github', link: 'https://www.github.com/trevorsandy'}
  - {icon: 'linkedin', link: 'http://www.linkedin.com/in/trevor-sandy-4193a122/'}
  - {icon: 'twitter', link: 'https://twitter.com/tds2142'}
  - {icon: 'envelope', link: 'mailto:trevor.sandy@gmail.com'}
